### PR TITLE
Made UIExpandingTableViewCell an optional protocol

### PR DESCRIPTION
**Pull request by afanslau**
as per issue #34. Documentation would still be nice
Thanks for creating this!

### CODE REVIEW

**Comment by OliverLetterer** [comment]
Thank you very much for this pull request. Always great to have people contributing back :) My time is very limited at the moment so I'm sorry for this and maybe future late responses. What I would like to discuss before merging this in is, if we should make all methods and properties of the `UIExpandingTableViewCell` protocol optional or if the protocol itself should be optional. The current approach allows a UITableViewCell to implement `@property (nonatomic, readonly) UIExpansionStyle expansionStyle;` while not implementing `- (void)setExpansionStyle:(UIExpansionStyle)style animated:(BOOL)animated;`. I'm not very comfortable with this inconsistent state.

What if instead we make the whole protocol optional. That is we make `- (UITableViewCell<UIExpandingTableViewCell> *)tableView:(SLExpandableTableView *)tableView expandingCellForSection:(NSInteger)section` return a plain `UITableViewCell` and document that it can optionally implement the whole `UIExpandingTableViewCell` protocol?

**Comment by afanslau** [comment]
Hey Oliver, I think that would definitely be averted plan. I already added the responds to selector check for all the methods so it should only be a change of return type right? Or would we have to cast the cell every time?

Thanks for the response!

Adam

**Comment by OliverLetterer** [comment]
If think is it more futureproofed if if we don't check each selector but rather if the `-[cell conformsToProtocol:]`.

**Comment by afanslau** [comment]
Agreed, so I'll switch to using conformsToProtocol, change the return type
to plain UITableViewCell objects and remove the optional status of the
protocol methods. I'll do it when I get off work :). Then I'll submit
another pull request. Thanks again for a great library

Best,
Adam

**Comment by OliverLetterer** [comment]
Sound awesome. Thank you very much. Really, always great to have people contributing back 👍🎉😃

**Pull request closed without merging**
